### ISSUE TITLE
Missing scripts in the prefabs ( pareto-quest-demo)

### ISSUE THREAD

**Issue by ericwang0701** [joaobelo92/auit#7]
Amazing work! Since I don't have the HoloLens, I'd like to try the pareto-quest-demo branch with my Oculus Quest 2. However, it seems the imported prefabs have some issues with missing scripts as shown in the below figures. Do you mind sharing the prefab setup so I can attach the right scripts? Or I think the issue might be solved if the .meta files are included in the repo.

Thank you so much for your help and time. Looking forward to trying it out.

![image](https://github.com/joaobelo92/auit/assets/1519164/7632b018-5695-46a9-96ac-7e4c44133903)
![image](https://github.com/joaobelo92/auit/assets/1519164/9c416025-cb6f-493b-b544-f50d10dda1d9)

**Comment by joaobelo92** [comment]
Hi Eric, thanks for reaching out!
The pareto-quest-demo branch was used solely for demonstration purposes for our upcoming UIST paper and we do not plan to continue development there as we have limited resources. However, I am currently preparing a new release of AUIT on the auit-pareto-release branch that will include all the new features. I could create a Quest2 demo there if you'd like to try it out. 
Are you planning to use AUIT on your research? I'd be happy to chat and give you a proper introduction to the toolkit and ongoing developments, as the documentation is quite limited at the moment.
